# Generated by Django 4.1 on 2022-08-16 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='win_percentage',
            new_name='losses',
        ),
    ]
