# Generated by Django 4.1 on 2022-08-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_win_percentage_profile_losses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='losses',
            field=models.IntegerField(default=0),
        ),
    ]
