# Generated by Django 4.1 on 2022-10-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_scoreboard_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='scoreboard_name',
        ),
    ]
