# Generated by Django 4.1 on 2022-08-11 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordsdata',
            fields=[
                ('word', models.TextField(null=True)),
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startday', models.IntegerField(default=0)),
                ('totalscore', models.IntegerField(default=0)),
                ('day1', models.CharField(default='-', max_length=5)),
                ('day2', models.CharField(default='-', max_length=5)),
                ('day3', models.CharField(default='-', max_length=5)),
                ('day4', models.CharField(default='-', max_length=5)),
                ('day5', models.CharField(default='-', max_length=5)),
                ('day6', models.CharField(default='-', max_length=5)),
                ('day7', models.CharField(default='-', max_length=5)),
                ('day8', models.CharField(default='-', max_length=5)),
                ('day9', models.CharField(default='-', max_length=5)),
                ('day10', models.CharField(default='-', max_length=5)),
                ('day11', models.CharField(default='-', max_length=5)),
                ('day12', models.CharField(default='-', max_length=5)),
                ('day13', models.CharField(default='-', max_length=5)),
                ('day14', models.CharField(default='-', max_length=5)),
                ('day15', models.CharField(default='-', max_length=5)),
                ('day16', models.CharField(default='-', max_length=5)),
                ('day17', models.CharField(default='-', max_length=5)),
                ('day18', models.CharField(default='-', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
