# Generated by Django 4.1 on 2022-08-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoreboard',
            old_name='startday',
            new_name='day',
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='guess1',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='guess2',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='guess3',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='guess4',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='guess5',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='guess6',
            field=models.CharField(default='', max_length=5),
        ),
    ]
