# Generated by Django 4.1 on 2022-08-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_startday_scoreboard_day_scoreboard_guess1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='guess1',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='guess2',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='guess3',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='guess4',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='guess5',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='guess6',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
