# Generated by Django 4.1 on 2022-08-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_scoreboard_guess1_alter_scoreboard_guess2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='startday',
            field=models.IntegerField(default=0),
        ),
    ]
