# Generated by Django 4.1 on 2022-08-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_scoreboard_startday'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewWordsdata',
            fields=[
                ('word', models.TextField(null=True)),
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
