# Generated by Django 4.1 on 2022-10-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_message_user_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date_created',
        ),
    ]
