# Generated by Django 4.1 on 2022-10-07 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_message_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
