# Generated by Django 4.1 on 2022-10-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newwordsdata',
            old_name='id',
            new_name='idnewword',
        ),
        migrations.RenameField(
            model_name='wordsdata',
            old_name='id',
            new_name='idword',
        ),
    ]
