# Generated by Django 4.1 on 2022-10-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_message_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newwordsdata',
            old_name='idnewword',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='wordsdata',
            old_name='idword',
            new_name='id',
        ),
    ]
